name: 'Cppcheck test'
desciption: 'Run cppcheck'
author: 'rafaelcorsi'

inputs:
  c_file:
    description: 'C file name and path'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install python
      shell: bash
      run: |
          python -m pip install --upgrade pip
          pip install pytest toml

    - name: Install cppcheck
      shell: bash
      run: |
        sudo apt install cppcheck

    - name: cppcheck
      shell: bash
      env:
        WOKWI_CLI_TOKEN: ${{ inputs.token}}
      run: |
        cppcheck --enable=all --suppress=missingIncludeSystem  --suppress=unmatchedSuppression --suppress=unusedFunction --suppress=invalidPrintfArgType_sint --suppress=invalidPrintfArgType_uint --error-exitcode=2 "${{inputs.c_file}}"
